version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Setup global Dependencies
          command: npm install firebase-tools -g
      - run:
          name: Build project
          command: CI=false npm run build
      - run:
          name: Deploy to firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
          
          
#- save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths:
#            - ./node_modules
