defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  
  

  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to Production
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN



workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build
      - deploy-prod:
        type: approval
          requires:
            - build
      


# version: 2
# jobs:
#   build:
#     branches:
#       ignore:
#         - gh-pages
#     docker:
#       - image: circleci/node:8
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#           - dependencies-{{ checksum "package.json" }}
#           - dependencies-
#       - run:
#           name: Install dependencies
#           command: npm install
#       - save_cache:
#           paths:
#             - node_modules
#           key: dependencies-{{ checksum "package.json" }}
#       - deploy:
#           name: Deploy
#           command: |
#               set -e
#               npm install
#               CI="" npm run build

#               remote=$(git config remote.origin.url)

#               siteSource="build"

#               if [ ! -d "build" ]
#               then
#                   echo "Usage: $0 <site source dir>"
#                   exit 1
#               fi

#               mkdir gh-pages-branch
#               cd gh-pages-branch
#               git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
#               git config --global user.name "$GH_NAME" > /dev/null 2>&1
#               git init
#               git remote add --fetch origin "$remote"

#               if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
#               then
#                   git checkout gh-pages
#                   git rm -rf .
#               else
#                   git checkout --orphan gh-pages
#               fi

#               cp -a "../build/." .

#               git add -A
#               git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
#               git push --force --quiet origin gh-pages > /dev/null 2>&1

#               cd ..
#               rm -rf gh-pages-branch

#               echo "Finished Deployment!"
